#! /bin/bash

# Install prerequisites
sudo apt install cmake

mkdir tmp

# mkplugins
git clone https://github.com/madskjeldgaard/mkplugins.git tmp/mkplugins

# Get sc source code
git clone --recurse-submodules https://github.com/supercollider/supercollider.git tmp/supercollider

# Start build process
INSTALL_DIR=$HOME/local/share/SuperCollider/Extensions
SC_DIR=$HOME/tmp/supercollider

cd tmp/mkplugins
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE='Release' -DSC_PATH=${SC_DIR} -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}
cmake --build . --config Release
cmake --build . --config Release --target install

# Clean up
cd $HOME
rm -rf $HOME/tmp/mkplugins
rm -rf $HOME/tmp/supercollider
