#! /bin/bash

# Install prerequisites
sudo apt install cmake # Raspberry OS
# sudo pacman -S cmake # ALARM

# portedplugins
git clone --recurse-submodules https://github.com/madskjeldgaard/portedplugins.git /tmp/portedplugins

# Get sc source code
git clone --recurse-submodules https://github.com/supercollider/supercollider.git /tmp/supercollider

# Start build process
INSTALL_DIR=$HOME/local/share/SuperCollider/Extensions
SC_DIR=/tmp/supercollider

cd /tmp/portedplugins || 'exit'
echo "Making build directory... "
mkdir build
cd build || 'exit'

echo "Starting build from $(pwd)"
cmake .. -DCMAKE_BUILD_TYPE='Release' -DSC_PATH="${SC_DIR}" -DCMAKE_INSTALL_PREFIX="${INSTALL_DIR}"
cmake --build . --config Release
cmake --build . --config Release --target install

# Clean up
# rm -rf /tmp/portedplugins
# rm -rf /tmp/supercollider
